name: Build Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build -o gitdl.exe
      - name: Upload to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: gitdl.exe
          path: gitdl.exe
